Bicycle Management
zevik7/b4b-shop pull request #13
Opened 2022-06-10 10:34 UTC by gioiemhuynh

2022-06-11 04:29 UTC, nguyendang127 approved these changes
Its look good ! Nice

2022-06-11 12:29 UTC, zevik7 approved these changes

2022-06-11 12:32 UTC, zevik7 requested changes
I think you should edit your commit message, It should follow name of your branch

2022-06-11 15:37 UTC, huynhvangioiem commented
OK, I just changed it! Thanks

2022-06-11 16:01 UTC, trucho1001 approved these changes

2022-06-12 05:47 UTC, zevik7 approved these changes

2022-06-12 06:03 UTC, trucho1001 approved these changes

2022-06-12 06:19 UTC, merged